name: grip3
channels:
  - nvidia/label/cuda-11.7.0
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - absl-py=2.3.1
  - accelerate=1.12.0
  - alsa-lib=1.2.14
  - aom=3.9.1
  - attr=2.5.2
  - blosc=1.21.6
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - chex=0.1.86
  - colorama=0.4.6
  - contourpy=1.3.2
  - cpython=3.10.19
  - cuda=11.7.0
  - cuda-cccl=11.7.58
  - cuda-command-line-tools=11.7.0
  - cuda-compiler=11.7.0
  - cuda-cudart=12.9.79
  - cuda-cudart-dev=11.7.60
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=11.7.50
  - cuda-cupti=11.7.50
  - cuda-cuxxfilt=11.7.50
  - cuda-demo-suite=11.7.50
  - cuda-documentation=11.7.50
  - cuda-driver-dev=11.7.60
  - cuda-gdb=11.7.50
  - cuda-libraries=11.7.0
  - cuda-libraries-dev=11.7.0
  - cuda-memcheck=11.7.50
  - cuda-nsight=11.7.50
  - cuda-nsight-compute=11.7.0
  - cuda-nvcc=11.7.64
  - cuda-nvdisasm=11.7.50
  - cuda-nvml-dev=11.7.50
  - cuda-nvprof=11.7.50
  - cuda-nvprune=11.7.50
  - cuda-nvrtc=11.7.50
  - cuda-nvrtc-dev=11.7.50
  - cuda-nvtx=11.7.50
  - cuda-nvvp=11.7.50
  - cuda-runtime=11.7.0
  - cuda-sanitizer-api=11.7.50
  - cuda-toolkit=11.7.0
  - cuda-tools=11.7.0
  - cuda-version=12.9
  - cuda-visual-tools=11.7.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - defusedxml=0.7.1
  - double-conversion=3.3.1
  - etils=1.12.2
  - ffmpeg=8.0.0
  - flax=0.10.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.0
  - freeglut=3.2.2
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - gds-tools=1.3.0.44
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - glib=2.86.2
  - glib-tools=2.86.2
  - glslang=16.0.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gst-plugins-base=1.26.8
  - gst-plugins-good=1.18.5
  - gstreamer=1.26.8
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - huggingface_hub=0.36.0
  - humanize=4.14.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imath=3.2.2
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - importlib_resources=6.5.2
  - intel-gmmlib=22.8.2
  - intel-media-driver=25.3.4
  - jack=1.9.22
  - jasper=4.2.8
  - jinja2=3.1.6
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - level-zero=1.26.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.6
  - libclang13=21.1.6
  - libcublas=11.10.1.25
  - libcublas-dev=11.10.1.25
  - libcufft=10.7.2.50
  - libcufft-dev=10.7.2.50
  - libcufile=1.3.0.44
  - libcufile-dev=1.3.0.44
  - libcups=2.3.3
  - libcurand=10.2.10.50
  - libcurand-dev=10.2.10.50
  - libcurl=8.17.0
  - libcusolver=11.3.5.50
  - libcusolver-dev=11.3.5.50
  - libcusparse=11.7.3.50
  - libcusparse-dev=11.7.3.50
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgrpc=1.74.1
  - libhwloc=2.12.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libllvm21=21.1.6
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnpp=11.7.3.21
  - libnpp-dev=11.7.3.21
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjpeg=11.7.2.34
  - libnvjpeg-dev=11.7.2.34
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopencv=4.12.0
  - libopengl=1.7.0
  - libopenvino=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-intel-cpu-plugin=2025.2.0
  - libopenvino-intel-gpu-plugin=2025.2.0
  - libopenvino-intel-npu-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.51
  - libpq=18.1
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - librealsense=2.56.5
  - librsvg=2.60.0
  - libsndfile=1.2.2
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=257.10
  - libtiff=4.7.1
  - libtorch=2.7.1
  - libudev1=257.10
  - libunwind=1.8.3
  - liburing=2.12
  - libusb=1.0.29
  - libuuid=2.41.2
  - libuv=1.51.0
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.14.1
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - lz4-c=1.10.0
  - markdown-it-py=4.0.0
  - matplotlib-base=3.10.8
  - mdurl=0.1.2
  - ml_dtypes=0.5.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nomkl=1.0
  - nsight-compute=2022.2.0.13
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - opencv=4.12.0
  - openexr=3.4.4
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openjph=0.25.3
  - openldap=2.6.10
  - openssl=3.6.0
  - opt-einsum=3.4.0
  - opt_einsum=3.4.0
  - optax=0.2.2
  - optree=0.18.0
  - orbax-checkpoint=0.6.4
  - packaging=25.0
  - pandas=2.3.3
  - pandas-stubs=2.3.2.250926
  - pango=1.56.4
  - pcre2=10.46
  - pixman=0.46.4
  - psutil=7.1.3
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - py-opencv=4.12.0
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyrealsense2=2.56.5
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-gil=3.10.19
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.9.3
  - rav1e=0.7.1
  - re2=2025.11.05
  - readline=8.2
  - regex=2025.11.3
  - requests=2.32.5
  - rich=14.2.0
  - safetensors=0.7.0
  - sdl2=2.32.56
  - sdl3=3.2.26
  - shaderc=2025.4
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - spirv-tools=2025.4
  - supervision=0.25.1
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2022.3.0
  - tensorstore=0.1.65
  - tk=8.6.13
  - toolz=1.1.0
  - tqdm=4.67.1
  - treescope=0.1.10
  - types-pytz=2025.2.0.20251108
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - urllib3=2.5.0
  - wayland=1.24.0
  - wayland-protocols=1.46
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxshmfence=1.3.3
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib-ng=2.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - addict==2.4.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - blinker==1.9.0
      - click==8.3.1
      - cmake==4.2.0
      - coloredlogs==15.0
      - comm==0.2.3
      - configargparse==1.7.1
      - cython==0.29.37
      - dash==3.3.0
      - decorator==5.2.1
      - easydict==1.9
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flask==3.1.2
      - fsspec==2025.9.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.7
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - jedi==0.19.2
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - lit==18.1.8
      - markdown==3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - meshcat==0.3.2
      - narwhals==2.13.0
      - nbformat==5.10.4
      - networkx==3.3
      - nibabel==3.2.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-python==4.12.0.88
      - parso==0.8.5
      - peft==0.18.0
      - pexpect==4.9.0
      - pillow==11.3.0
      - pip==25.3
      - platformdirs==4.5.0
      - plotly==6.5.0
      - pointnet2-ops==3.0.0
      - prompt-toolkit==3.0.52
      - protobuf==3.20.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyngrok==7.5.0
      - pyquaternion==0.9.9
      - pyyaml==5.4.1
      - pyzmq==27.1.0
      - referencing==0.37.0
      - retrying==1.4.2
      - rpds-py==0.30.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - setuptools==44.1.1
      - shellingham==1.5.4
      - stack-data==0.6.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.1
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.3.1+cu121
      - torchvision==0.18.1+cu121
      - tornado==6.5.2
      - traitlets==5.14.3
      - transformers==4.57.3
      - trimesh==4.10.0
      - triton==2.3.1
      - typer-slim==0.20.0
      - u-msgpack-python==2.8.0
      - ur-rtde==1.6.2
      - vtk-visualizer==0.9.6
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
prefix: /home/au-robotics/anaconda3/envs/grip3
